export const ActionTypes = {
  //--------------QUESTION Action Types
  GET_QUESTION_LIST_START: 'GET_QUESTION_LIST_START',
  GET_QUESTION_LIST_SUCCESS: 'GET_QUESTION_LIST_SUCCESS',
  UPDATE_QUESTION_ANSWER: 'UPDATE_QUESTION_ANSWER',
};
